/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateDockerhubTarget
 */
public class CreateDockerhubTargetTest {
    private final CreateDockerhubTarget model = new CreateDockerhubTarget();

    /**
     * Model tests for CreateDockerhubTarget
     */
    @Test
    public void testCreateDockerhubTarget() {
        // TODO: test CreateDockerhubTarget
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'dockerhubPassword'
     */
    @Test
    public void dockerhubPasswordTest() {
        // TODO: test dockerhubPassword
    }

    /**
     * Test the property 'dockerhubUsername'
     */
    @Test
    public void dockerhubUsernameTest() {
        // TODO: test dockerhubUsername
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'uidToken'
     */
    @Test
    public void uidTokenTest() {
        // TODO: test uidToken
    }

}
