/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Encrypt
 */
public class EncryptTest {
    private final Encrypt model = new Encrypt();

    /**
     * Model tests for Encrypt
     */
    @Test
    public void testEncrypt() {
        // TODO: test Encrypt
    }

    /**
     * Test the property 'encryptionContext'
     */
    @Test
    public void encryptionContextTest() {
        // TODO: test encryptionContext
    }

    /**
     * Test the property 'keyName'
     */
    @Test
    public void keyNameTest() {
        // TODO: test keyName
    }

    /**
     * Test the property 'plaintext'
     */
    @Test
    public void plaintextTest() {
        // TODO: test plaintext
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'uidToken'
     */
    @Test
    public void uidTokenTest() {
        // TODO: test uidToken
    }

}
