/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.akeyless.client.model.ConfigChange;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GatewayCreateK8SAuthConfigOutput
 */
public class GatewayCreateK8SAuthConfigOutputTest {
    private final GatewayCreateK8SAuthConfigOutput model = new GatewayCreateK8SAuthConfigOutput();

    /**
     * Model tests for GatewayCreateK8SAuthConfigOutput
     */
    @Test
    public void testGatewayCreateK8SAuthConfigOutput() {
        // TODO: test GatewayCreateK8SAuthConfigOutput
    }

    /**
     * Test the property 'clusterId'
     */
    @Test
    public void clusterIdTest() {
        // TODO: test clusterId
    }

    /**
     * Test the property 'partsChange'
     */
    @Test
    public void partsChangeTest() {
        // TODO: test partsChange
    }

    /**
     * Test the property 'totalHash'
     */
    @Test
    public void totalHashTest() {
        // TODO: test totalHash
    }

}
