/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.akeyless.client.model.CustomerFullAddress;
import io.akeyless.client.model.SmInfo;
import io.akeyless.client.model.SraInfo;
import io.akeyless.client.model.SystemAccessCredsSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetAccountSettingsCommandOutput
 */
public class GetAccountSettingsCommandOutputTest {
    private final GetAccountSettingsCommandOutput model = new GetAccountSettingsCommandOutput();

    /**
     * Model tests for GetAccountSettingsCommandOutput
     */
    @Test
    public void testGetAccountSettingsCommandOutput() {
        // TODO: test GetAccountSettingsCommandOutput
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'secretManagement'
     */
    @Test
    public void secretManagementTest() {
        // TODO: test secretManagement
    }

    /**
     * Test the property 'secureRemoteAccess'
     */
    @Test
    public void secureRemoteAccessTest() {
        // TODO: test secureRemoteAccess
    }

    /**
     * Test the property 'systemAccessCredsSettings'
     */
    @Test
    public void systemAccessCredsSettingsTest() {
        // TODO: test systemAccessCredsSettings
    }

}
