/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.akeyless.client.model.SlackNotiForwarderDetails;
import io.akeyless.client.model.TeamsNotiForwarderDetails;
import io.akeyless.client.model.WebhookNotiForwarderDetails;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NotiForwarderDetailsInput
 */
public class NotiForwarderDetailsInputTest {
    private final NotiForwarderDetailsInput model = new NotiForwarderDetailsInput();

    /**
     * Model tests for NotiForwarderDetailsInput
     */
    @Test
    public void testNotiForwarderDetailsInput() {
        // TODO: test NotiForwarderDetailsInput
    }

    /**
     * Test the property 'appPrivateKeyPemBase64'
     */
    @Test
    public void appPrivateKeyPemBase64Test() {
        // TODO: test appPrivateKeyPemBase64
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'slackNotiForwarderDetails'
     */
    @Test
    public void slackNotiForwarderDetailsTest() {
        // TODO: test slackNotiForwarderDetails
    }

    /**
     * Test the property 'teamsNotiForwarderDetails'
     */
    @Test
    public void teamsNotiForwarderDetailsTest() {
        // TODO: test teamsNotiForwarderDetails
    }

    /**
     * Test the property 'webhookNotiForwarderDetails'
     */
    @Test
    public void webhookNotiForwarderDetailsTest() {
        // TODO: test webhookNotiForwarderDetails
    }

}
