/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PKICertificateIssueDetails
 */
public class PKICertificateIssueDetailsTest {
    private final PKICertificateIssueDetails model = new PKICertificateIssueDetails();

    /**
     * Model tests for PKICertificateIssueDetails
     */
    @Test
    public void testPKICertificateIssueDetails() {
        // TODO: test PKICertificateIssueDetails
    }

    /**
     * Test the property 'allowAnyName'
     */
    @Test
    public void allowAnyNameTest() {
        // TODO: test allowAnyName
    }

    /**
     * Test the property 'allowSubdomains'
     */
    @Test
    public void allowSubdomainsTest() {
        // TODO: test allowSubdomains
    }

    /**
     * Test the property 'allowedDomainsList'
     */
    @Test
    public void allowedDomainsListTest() {
        // TODO: test allowedDomainsList
    }

    /**
     * Test the property 'allowedUriSans'
     */
    @Test
    public void allowedUriSansTest() {
        // TODO: test allowedUriSans
    }

    /**
     * Test the property 'basicConstraintsValidForNonCa'
     */
    @Test
    public void basicConstraintsValidForNonCaTest() {
        // TODO: test basicConstraintsValidForNonCa
    }

    /**
     * Test the property 'clientFlag'
     */
    @Test
    public void clientFlagTest() {
        // TODO: test clientFlag
    }

    /**
     * Test the property 'codeSigningFlag'
     */
    @Test
    public void codeSigningFlagTest() {
        // TODO: test codeSigningFlag
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'enforceHostnames'
     */
    @Test
    public void enforceHostnamesTest() {
        // TODO: test enforceHostnames
    }

    /**
     * Test the property 'isCa'
     */
    @Test
    public void isCaTest() {
        // TODO: test isCa
    }

    /**
     * Test the property 'keyBits'
     */
    @Test
    public void keyBitsTest() {
        // TODO: test keyBits
    }

    /**
     * Test the property 'keyType'
     */
    @Test
    public void keyTypeTest() {
        // TODO: test keyType
    }

    /**
     * Test the property 'keyUsageList'
     */
    @Test
    public void keyUsageListTest() {
        // TODO: test keyUsageList
    }

    /**
     * Test the property 'locality'
     */
    @Test
    public void localityTest() {
        // TODO: test locality
    }

    /**
     * Test the property 'notBeforeDuration'
     */
    @Test
    public void notBeforeDurationTest() {
        // TODO: test notBeforeDuration
    }

    /**
     * Test the property 'organizationList'
     */
    @Test
    public void organizationListTest() {
        // TODO: test organizationList
    }

    /**
     * Test the property 'organizationUnitList'
     */
    @Test
    public void organizationUnitListTest() {
        // TODO: test organizationUnitList
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'province'
     */
    @Test
    public void provinceTest() {
        // TODO: test province
    }

    /**
     * Test the property 'requireCn'
     */
    @Test
    public void requireCnTest() {
        // TODO: test requireCn
    }

    /**
     * Test the property 'serverFlag'
     */
    @Test
    public void serverFlagTest() {
        // TODO: test serverFlag
    }

    /**
     * Test the property 'streetAddress'
     */
    @Test
    public void streetAddressTest() {
        // TODO: test streetAddress
    }

}
