/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.akeyless.client.model.SAMLAttribute;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SAMLAccessRules
 */
public class SAMLAccessRulesTest {
    private final SAMLAccessRules model = new SAMLAccessRules();

    /**
     * Model tests for SAMLAccessRules
     */
    @Test
    public void testSAMLAccessRules() {
        // TODO: test SAMLAccessRules
    }

    /**
     * Test the property 'boundAttributes'
     */
    @Test
    public void boundAttributesTest() {
        // TODO: test boundAttributes
    }

    /**
     * Test the property 'idpMetadataUrl'
     */
    @Test
    public void idpMetadataUrlTest() {
        // TODO: test idpMetadataUrl
    }

    /**
     * Test the property 'idpMetadataXml'
     */
    @Test
    public void idpMetadataXmlTest() {
        // TODO: test idpMetadataXml
    }

    /**
     * Test the property 'uniqueIdentifier'
     */
    @Test
    public void uniqueIdentifierTest() {
        // TODO: test uniqueIdentifier
    }

}
