/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.akeyless.client.model.TargetError;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScanResults
 */
public class ScanResultsTest {
    private final ScanResults model = new ScanResults();

    /**
     * Model tests for ScanResults
     */
    @Test
    public void testScanResults() {
        // TODO: test ScanResults
    }

    /**
     * Test the property 'countExisting'
     */
    @Test
    public void countExistingTest() {
        // TODO: test countExisting
    }

    /**
     * Test the property 'countFailed'
     */
    @Test
    public void countFailedTest() {
        // TODO: test countFailed
    }

    /**
     * Test the property 'countHosts'
     */
    @Test
    public void countHostsTest() {
        // TODO: test countHosts
    }

    /**
     * Test the property 'countNew'
     */
    @Test
    public void countNewTest() {
        // TODO: test countNew
    }

    /**
     * Test the property 'countSubdomains'
     */
    @Test
    public void countSubdomainsTest() {
        // TODO: test countSubdomains
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'failedTargets'
     */
    @Test
    public void failedTargetsTest() {
        // TODO: test failedTargets
    }

    /**
     * Test the property 'itemNames'
     */
    @Test
    public void itemNamesTest() {
        // TODO: test itemNames
    }

}
