/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TargetCreateGitlab
 */
public class TargetCreateGitlabTest {
    private final TargetCreateGitlab model = new TargetCreateGitlab();

    /**
     * Model tests for TargetCreateGitlab
     */
    @Test
    public void testTargetCreateGitlab() {
        // TODO: test TargetCreateGitlab
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'gitlabAccessToken'
     */
    @Test
    public void gitlabAccessTokenTest() {
        // TODO: test gitlabAccessToken
    }

    /**
     * Test the property 'gitlabCertificate'
     */
    @Test
    public void gitlabCertificateTest() {
        // TODO: test gitlabCertificate
    }

    /**
     * Test the property 'gitlabUrl'
     */
    @Test
    public void gitlabUrlTest() {
        // TODO: test gitlabUrl
    }

    /**
     * Test the property 'json'
     */
    @Test
    public void jsonTest() {
        // TODO: test json
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'maxVersions'
     */
    @Test
    public void maxVersionsTest() {
        // TODO: test maxVersions
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'uidToken'
     */
    @Test
    public void uidTokenTest() {
        // TODO: test uidToken
    }

}
