/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateAuthMethodAzureAD
 */
public class UpdateAuthMethodAzureADTest {
    private final UpdateAuthMethodAzureAD model = new UpdateAuthMethodAzureAD();

    /**
     * Model tests for UpdateAuthMethodAzureAD
     */
    @Test
    public void testUpdateAuthMethodAzureAD() {
        // TODO: test UpdateAuthMethodAzureAD
    }

    /**
     * Test the property 'accessExpires'
     */
    @Test
    public void accessExpiresTest() {
        // TODO: test accessExpires
    }

    /**
     * Test the property 'audience'
     */
    @Test
    public void audienceTest() {
        // TODO: test audience
    }

    /**
     * Test the property 'boundGroupId'
     */
    @Test
    public void boundGroupIdTest() {
        // TODO: test boundGroupId
    }

    /**
     * Test the property 'boundIps'
     */
    @Test
    public void boundIpsTest() {
        // TODO: test boundIps
    }

    /**
     * Test the property 'boundProviders'
     */
    @Test
    public void boundProvidersTest() {
        // TODO: test boundProviders
    }

    /**
     * Test the property 'boundResourceId'
     */
    @Test
    public void boundResourceIdTest() {
        // TODO: test boundResourceId
    }

    /**
     * Test the property 'boundResourceNames'
     */
    @Test
    public void boundResourceNamesTest() {
        // TODO: test boundResourceNames
    }

    /**
     * Test the property 'boundResourceTypes'
     */
    @Test
    public void boundResourceTypesTest() {
        // TODO: test boundResourceTypes
    }

    /**
     * Test the property 'boundRgId'
     */
    @Test
    public void boundRgIdTest() {
        // TODO: test boundRgId
    }

    /**
     * Test the property 'boundSpid'
     */
    @Test
    public void boundSpidTest() {
        // TODO: test boundSpid
    }

    /**
     * Test the property 'boundSubId'
     */
    @Test
    public void boundSubIdTest() {
        // TODO: test boundSubId
    }

    /**
     * Test the property 'boundTenantId'
     */
    @Test
    public void boundTenantIdTest() {
        // TODO: test boundTenantId
    }

    /**
     * Test the property 'forceSubClaims'
     */
    @Test
    public void forceSubClaimsTest() {
        // TODO: test forceSubClaims
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'jwksUri'
     */
    @Test
    public void jwksUriTest() {
        // TODO: test jwksUri
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'newName'
     */
    @Test
    public void newNameTest() {
        // TODO: test newName
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'uidToken'
     */
    @Test
    public void uidTokenTest() {
        // TODO: test uidToken
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

}
