/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VaultAddressOutput
 */
public class VaultAddressOutputTest {
    private final VaultAddressOutput model = new VaultAddressOutput();

    /**
     * Model tests for VaultAddressOutput
     */
    @Test
    public void testVaultAddressOutput() {
        // TODO: test VaultAddressOutput
    }

    /**
     * Test the property 'apiGwUrl'
     */
    @Test
    public void apiGwUrlTest() {
        // TODO: test apiGwUrl
    }

    /**
     * Test the property 'vaultUrl'
     */
    @Test
    public void vaultUrlTest() {
        // TODO: test vaultUrl
    }

}
