/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.akeyless.client.model.AgenticRule;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.akeyless.client.JSON;

/**
 * AgenticRules
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AgenticRules {
  public static final String SERIALIZED_NAME_INPUT_RULES = "input_rules";
  @SerializedName(SERIALIZED_NAME_INPUT_RULES)
  @javax.annotation.Nullable
  private List<AgenticRule> inputRules = new ArrayList<>();

  public static final String SERIALIZED_NAME_OUTPUT_RULES = "output_rules";
  @SerializedName(SERIALIZED_NAME_OUTPUT_RULES)
  @javax.annotation.Nullable
  private List<AgenticRule> outputRules = new ArrayList<>();

  public AgenticRules() {
  }

  public AgenticRules inputRules(@javax.annotation.Nullable List<AgenticRule> inputRules) {
    this.inputRules = inputRules;
    return this;
  }

  public AgenticRules addInputRulesItem(AgenticRule inputRulesItem) {
    if (this.inputRules == null) {
      this.inputRules = new ArrayList<>();
    }
    this.inputRules.add(inputRulesItem);
    return this;
  }

  /**
   * Get inputRules
   * @return inputRules
   */
  @javax.annotation.Nullable
  public List<AgenticRule> getInputRules() {
    return inputRules;
  }

  public void setInputRules(@javax.annotation.Nullable List<AgenticRule> inputRules) {
    this.inputRules = inputRules;
  }


  public AgenticRules outputRules(@javax.annotation.Nullable List<AgenticRule> outputRules) {
    this.outputRules = outputRules;
    return this;
  }

  public AgenticRules addOutputRulesItem(AgenticRule outputRulesItem) {
    if (this.outputRules == null) {
      this.outputRules = new ArrayList<>();
    }
    this.outputRules.add(outputRulesItem);
    return this;
  }

  /**
   * Get outputRules
   * @return outputRules
   */
  @javax.annotation.Nullable
  public List<AgenticRule> getOutputRules() {
    return outputRules;
  }

  public void setOutputRules(@javax.annotation.Nullable List<AgenticRule> outputRules) {
    this.outputRules = outputRules;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgenticRules agenticRules = (AgenticRules) o;
    return Objects.equals(this.inputRules, agenticRules.inputRules) &&
        Objects.equals(this.outputRules, agenticRules.outputRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputRules, outputRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgenticRules {\n");
    sb.append("    inputRules: ").append(toIndentedString(inputRules)).append("\n");
    sb.append("    outputRules: ").append(toIndentedString(outputRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("input_rules");
    openapiFields.add("output_rules");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AgenticRules
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AgenticRules.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AgenticRules is not found in the empty JSON string", AgenticRules.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AgenticRules.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AgenticRules` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("input_rules") != null && !jsonObj.get("input_rules").isJsonNull()) {
        JsonArray jsonArrayinputRules = jsonObj.getAsJsonArray("input_rules");
        if (jsonArrayinputRules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("input_rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `input_rules` to be an array in the JSON string but got `%s`", jsonObj.get("input_rules").toString()));
          }

          // validate the optional field `input_rules` (array)
          for (int i = 0; i < jsonArrayinputRules.size(); i++) {
            AgenticRule.validateJsonElement(jsonArrayinputRules.get(i));
          };
        }
      }
      if (jsonObj.get("output_rules") != null && !jsonObj.get("output_rules").isJsonNull()) {
        JsonArray jsonArrayoutputRules = jsonObj.getAsJsonArray("output_rules");
        if (jsonArrayoutputRules != null) {
          // ensure the json data is an array
          if (!jsonObj.get("output_rules").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `output_rules` to be an array in the JSON string but got `%s`", jsonObj.get("output_rules").toString()));
          }

          // validate the optional field `output_rules` (array)
          for (int i = 0; i < jsonArrayoutputRules.size(); i++) {
            AgenticRule.validateJsonElement(jsonArrayoutputRules.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AgenticRules.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AgenticRules' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AgenticRules> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AgenticRules.class));

       return (TypeAdapter<T>) new TypeAdapter<AgenticRules>() {
           @Override
           public void write(JsonWriter out, AgenticRules value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AgenticRules read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AgenticRules given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AgenticRules
   * @throws IOException if the JSON string is invalid with respect to AgenticRules
   */
  public static AgenticRules fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AgenticRules.class);
  }

  /**
   * Convert an instance of AgenticRules to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

