/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.akeyless.client.JSON;

/**
 * AzureTargetDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class AzureTargetDetails {
  public static final String SERIALIZED_NAME_AZURE_CLIENT_ID = "azure_client_id";
  @SerializedName(SERIALIZED_NAME_AZURE_CLIENT_ID)
  @javax.annotation.Nullable
  private String azureClientId;

  public static final String SERIALIZED_NAME_AZURE_CLIENT_SECRET = "azure_client_secret";
  @SerializedName(SERIALIZED_NAME_AZURE_CLIENT_SECRET)
  @javax.annotation.Nullable
  private String azureClientSecret;

  public static final String SERIALIZED_NAME_AZURE_RESOURCE_GROUP_NAME = "azure_resource_group_name";
  @SerializedName(SERIALIZED_NAME_AZURE_RESOURCE_GROUP_NAME)
  @javax.annotation.Nullable
  private String azureResourceGroupName;

  public static final String SERIALIZED_NAME_AZURE_RESOURCE_NAME = "azure_resource_name";
  @SerializedName(SERIALIZED_NAME_AZURE_RESOURCE_NAME)
  @javax.annotation.Nullable
  private String azureResourceName;

  public static final String SERIALIZED_NAME_AZURE_SUBSCRIPTION_ID = "azure_subscription_id";
  @SerializedName(SERIALIZED_NAME_AZURE_SUBSCRIPTION_ID)
  @javax.annotation.Nullable
  private String azureSubscriptionId;

  public static final String SERIALIZED_NAME_AZURE_TENANT_ID = "azure_tenant_id";
  @SerializedName(SERIALIZED_NAME_AZURE_TENANT_ID)
  @javax.annotation.Nullable
  private String azureTenantId;

  public static final String SERIALIZED_NAME_AZURE_USERNAME = "azure_username";
  @SerializedName(SERIALIZED_NAME_AZURE_USERNAME)
  @javax.annotation.Nullable
  private String azureUsername;

  public static final String SERIALIZED_NAME_CONNECTION_TYPE = "connection_type";
  @SerializedName(SERIALIZED_NAME_CONNECTION_TYPE)
  @javax.annotation.Nullable
  private String connectionType;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE = "expiration_date";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime expirationDate;

  public static final String SERIALIZED_NAME_GRACE_ROTATED_SECRET_KEY = "grace_rotated_secret_key";
  @SerializedName(SERIALIZED_NAME_GRACE_ROTATED_SECRET_KEY)
  @javax.annotation.Nullable
  private String graceRotatedSecretKey;

  public static final String SERIALIZED_NAME_USE_GW_CLOUD_IDENTITY = "use_gw_cloud_identity";
  @SerializedName(SERIALIZED_NAME_USE_GW_CLOUD_IDENTITY)
  @javax.annotation.Nullable
  private Boolean useGwCloudIdentity;

  public AzureTargetDetails() {
  }

  public AzureTargetDetails azureClientId(@javax.annotation.Nullable String azureClientId) {
    this.azureClientId = azureClientId;
    return this;
  }

  /**
   * Get azureClientId
   * @return azureClientId
   */
  @javax.annotation.Nullable
  public String getAzureClientId() {
    return azureClientId;
  }

  public void setAzureClientId(@javax.annotation.Nullable String azureClientId) {
    this.azureClientId = azureClientId;
  }


  public AzureTargetDetails azureClientSecret(@javax.annotation.Nullable String azureClientSecret) {
    this.azureClientSecret = azureClientSecret;
    return this;
  }

  /**
   * Get azureClientSecret
   * @return azureClientSecret
   */
  @javax.annotation.Nullable
  public String getAzureClientSecret() {
    return azureClientSecret;
  }

  public void setAzureClientSecret(@javax.annotation.Nullable String azureClientSecret) {
    this.azureClientSecret = azureClientSecret;
  }


  public AzureTargetDetails azureResourceGroupName(@javax.annotation.Nullable String azureResourceGroupName) {
    this.azureResourceGroupName = azureResourceGroupName;
    return this;
  }

  /**
   * Get azureResourceGroupName
   * @return azureResourceGroupName
   */
  @javax.annotation.Nullable
  public String getAzureResourceGroupName() {
    return azureResourceGroupName;
  }

  public void setAzureResourceGroupName(@javax.annotation.Nullable String azureResourceGroupName) {
    this.azureResourceGroupName = azureResourceGroupName;
  }


  public AzureTargetDetails azureResourceName(@javax.annotation.Nullable String azureResourceName) {
    this.azureResourceName = azureResourceName;
    return this;
  }

  /**
   * Get azureResourceName
   * @return azureResourceName
   */
  @javax.annotation.Nullable
  public String getAzureResourceName() {
    return azureResourceName;
  }

  public void setAzureResourceName(@javax.annotation.Nullable String azureResourceName) {
    this.azureResourceName = azureResourceName;
  }


  public AzureTargetDetails azureSubscriptionId(@javax.annotation.Nullable String azureSubscriptionId) {
    this.azureSubscriptionId = azureSubscriptionId;
    return this;
  }

  /**
   * Get azureSubscriptionId
   * @return azureSubscriptionId
   */
  @javax.annotation.Nullable
  public String getAzureSubscriptionId() {
    return azureSubscriptionId;
  }

  public void setAzureSubscriptionId(@javax.annotation.Nullable String azureSubscriptionId) {
    this.azureSubscriptionId = azureSubscriptionId;
  }


  public AzureTargetDetails azureTenantId(@javax.annotation.Nullable String azureTenantId) {
    this.azureTenantId = azureTenantId;
    return this;
  }

  /**
   * Get azureTenantId
   * @return azureTenantId
   */
  @javax.annotation.Nullable
  public String getAzureTenantId() {
    return azureTenantId;
  }

  public void setAzureTenantId(@javax.annotation.Nullable String azureTenantId) {
    this.azureTenantId = azureTenantId;
  }


  public AzureTargetDetails azureUsername(@javax.annotation.Nullable String azureUsername) {
    this.azureUsername = azureUsername;
    return this;
  }

  /**
   * Get azureUsername
   * @return azureUsername
   */
  @javax.annotation.Nullable
  public String getAzureUsername() {
    return azureUsername;
  }

  public void setAzureUsername(@javax.annotation.Nullable String azureUsername) {
    this.azureUsername = azureUsername;
  }


  public AzureTargetDetails connectionType(@javax.annotation.Nullable String connectionType) {
    this.connectionType = connectionType;
    return this;
  }

  /**
   * Get connectionType
   * @return connectionType
   */
  @javax.annotation.Nullable
  public String getConnectionType() {
    return connectionType;
  }

  public void setConnectionType(@javax.annotation.Nullable String connectionType) {
    this.connectionType = connectionType;
  }


  public AzureTargetDetails expirationDate(@javax.annotation.Nullable OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

  /**
   * Get expirationDate
   * @return expirationDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(@javax.annotation.Nullable OffsetDateTime expirationDate) {
    this.expirationDate = expirationDate;
  }


  public AzureTargetDetails graceRotatedSecretKey(@javax.annotation.Nullable String graceRotatedSecretKey) {
    this.graceRotatedSecretKey = graceRotatedSecretKey;
    return this;
  }

  /**
   * Get graceRotatedSecretKey
   * @return graceRotatedSecretKey
   */
  @javax.annotation.Nullable
  public String getGraceRotatedSecretKey() {
    return graceRotatedSecretKey;
  }

  public void setGraceRotatedSecretKey(@javax.annotation.Nullable String graceRotatedSecretKey) {
    this.graceRotatedSecretKey = graceRotatedSecretKey;
  }


  public AzureTargetDetails useGwCloudIdentity(@javax.annotation.Nullable Boolean useGwCloudIdentity) {
    this.useGwCloudIdentity = useGwCloudIdentity;
    return this;
  }

  /**
   * Get useGwCloudIdentity
   * @return useGwCloudIdentity
   */
  @javax.annotation.Nullable
  public Boolean getUseGwCloudIdentity() {
    return useGwCloudIdentity;
  }

  public void setUseGwCloudIdentity(@javax.annotation.Nullable Boolean useGwCloudIdentity) {
    this.useGwCloudIdentity = useGwCloudIdentity;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AzureTargetDetails azureTargetDetails = (AzureTargetDetails) o;
    return Objects.equals(this.azureClientId, azureTargetDetails.azureClientId) &&
        Objects.equals(this.azureClientSecret, azureTargetDetails.azureClientSecret) &&
        Objects.equals(this.azureResourceGroupName, azureTargetDetails.azureResourceGroupName) &&
        Objects.equals(this.azureResourceName, azureTargetDetails.azureResourceName) &&
        Objects.equals(this.azureSubscriptionId, azureTargetDetails.azureSubscriptionId) &&
        Objects.equals(this.azureTenantId, azureTargetDetails.azureTenantId) &&
        Objects.equals(this.azureUsername, azureTargetDetails.azureUsername) &&
        Objects.equals(this.connectionType, azureTargetDetails.connectionType) &&
        Objects.equals(this.expirationDate, azureTargetDetails.expirationDate) &&
        Objects.equals(this.graceRotatedSecretKey, azureTargetDetails.graceRotatedSecretKey) &&
        Objects.equals(this.useGwCloudIdentity, azureTargetDetails.useGwCloudIdentity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(azureClientId, azureClientSecret, azureResourceGroupName, azureResourceName, azureSubscriptionId, azureTenantId, azureUsername, connectionType, expirationDate, graceRotatedSecretKey, useGwCloudIdentity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AzureTargetDetails {\n");
    sb.append("    azureClientId: ").append(toIndentedString(azureClientId)).append("\n");
    sb.append("    azureClientSecret: ").append(toIndentedString(azureClientSecret)).append("\n");
    sb.append("    azureResourceGroupName: ").append(toIndentedString(azureResourceGroupName)).append("\n");
    sb.append("    azureResourceName: ").append(toIndentedString(azureResourceName)).append("\n");
    sb.append("    azureSubscriptionId: ").append(toIndentedString(azureSubscriptionId)).append("\n");
    sb.append("    azureTenantId: ").append(toIndentedString(azureTenantId)).append("\n");
    sb.append("    azureUsername: ").append(toIndentedString(azureUsername)).append("\n");
    sb.append("    connectionType: ").append(toIndentedString(connectionType)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    graceRotatedSecretKey: ").append(toIndentedString(graceRotatedSecretKey)).append("\n");
    sb.append("    useGwCloudIdentity: ").append(toIndentedString(useGwCloudIdentity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("azure_client_id");
    openapiFields.add("azure_client_secret");
    openapiFields.add("azure_resource_group_name");
    openapiFields.add("azure_resource_name");
    openapiFields.add("azure_subscription_id");
    openapiFields.add("azure_tenant_id");
    openapiFields.add("azure_username");
    openapiFields.add("connection_type");
    openapiFields.add("expiration_date");
    openapiFields.add("grace_rotated_secret_key");
    openapiFields.add("use_gw_cloud_identity");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AzureTargetDetails
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AzureTargetDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AzureTargetDetails is not found in the empty JSON string", AzureTargetDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AzureTargetDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AzureTargetDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("azure_client_id") != null && !jsonObj.get("azure_client_id").isJsonNull()) && !jsonObj.get("azure_client_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_client_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_client_id").toString()));
      }
      if ((jsonObj.get("azure_client_secret") != null && !jsonObj.get("azure_client_secret").isJsonNull()) && !jsonObj.get("azure_client_secret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_client_secret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_client_secret").toString()));
      }
      if ((jsonObj.get("azure_resource_group_name") != null && !jsonObj.get("azure_resource_group_name").isJsonNull()) && !jsonObj.get("azure_resource_group_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_resource_group_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_resource_group_name").toString()));
      }
      if ((jsonObj.get("azure_resource_name") != null && !jsonObj.get("azure_resource_name").isJsonNull()) && !jsonObj.get("azure_resource_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_resource_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_resource_name").toString()));
      }
      if ((jsonObj.get("azure_subscription_id") != null && !jsonObj.get("azure_subscription_id").isJsonNull()) && !jsonObj.get("azure_subscription_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_subscription_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_subscription_id").toString()));
      }
      if ((jsonObj.get("azure_tenant_id") != null && !jsonObj.get("azure_tenant_id").isJsonNull()) && !jsonObj.get("azure_tenant_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_tenant_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_tenant_id").toString()));
      }
      if ((jsonObj.get("azure_username") != null && !jsonObj.get("azure_username").isJsonNull()) && !jsonObj.get("azure_username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `azure_username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azure_username").toString()));
      }
      if ((jsonObj.get("connection_type") != null && !jsonObj.get("connection_type").isJsonNull()) && !jsonObj.get("connection_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `connection_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connection_type").toString()));
      }
      if ((jsonObj.get("grace_rotated_secret_key") != null && !jsonObj.get("grace_rotated_secret_key").isJsonNull()) && !jsonObj.get("grace_rotated_secret_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `grace_rotated_secret_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("grace_rotated_secret_key").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AzureTargetDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AzureTargetDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AzureTargetDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AzureTargetDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<AzureTargetDetails>() {
           @Override
           public void write(JsonWriter out, AzureTargetDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AzureTargetDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AzureTargetDetails given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AzureTargetDetails
   * @throws IOException if the JSON string is invalid with respect to AzureTargetDetails
   */
  public static AzureTargetDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AzureTargetDetails.class);
  }

  /**
   * Convert an instance of AzureTargetDetails to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

