/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * gatewayMigratePersonalItems is a command that migrate personal items from external vault
 */
@ApiModel(description = "gatewayMigratePersonalItems is a command that migrate personal items from external vault")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GatewayMigratePersonalItems {
  public static final String SERIALIZED_NAME_1PASSWORD_EMAIL = "1password-email";
  @SerializedName(SERIALIZED_NAME_1PASSWORD_EMAIL)
  private String _1passwordEmail;

  public static final String SERIALIZED_NAME_1PASSWORD_PASSWORD = "1password-password";
  @SerializedName(SERIALIZED_NAME_1PASSWORD_PASSWORD)
  private String _1passwordPassword;

  public static final String SERIALIZED_NAME_1PASSWORD_SECRET_KEY = "1password-secret-key";
  @SerializedName(SERIALIZED_NAME_1PASSWORD_SECRET_KEY)
  private String _1passwordSecretKey;

  public static final String SERIALIZED_NAME_1PASSWORD_URL = "1password-url";
  @SerializedName(SERIALIZED_NAME_1PASSWORD_URL)
  private String _1passwordUrl;

  public static final String SERIALIZED_NAME_1PASSWORD_VAULTS = "1password-vaults";
  @SerializedName(SERIALIZED_NAME_1PASSWORD_VAULTS)
  private List<String> _1passwordVaults = null;

  public static final String SERIALIZED_NAME_JSON = "json";
  @SerializedName(SERIALIZED_NAME_JSON)
  private Boolean json = false;

  public static final String SERIALIZED_NAME_PROTECTION_KEY = "protection-key";
  @SerializedName(SERIALIZED_NAME_PROTECTION_KEY)
  private String protectionKey;

  public static final String SERIALIZED_NAME_TARGET_LOCATION = "target-location";
  @SerializedName(SERIALIZED_NAME_TARGET_LOCATION)
  private String targetLocation;

  public static final String SERIALIZED_NAME_TOKEN = "token";
  @SerializedName(SERIALIZED_NAME_TOKEN)
  private String token;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type = "1password";

  public static final String SERIALIZED_NAME_UID_TOKEN = "uid-token";
  @SerializedName(SERIALIZED_NAME_UID_TOKEN)
  private String uidToken;

  public GatewayMigratePersonalItems() { 
  }

  public GatewayMigratePersonalItems _1passwordEmail(String _1passwordEmail) {
    
    this._1passwordEmail = _1passwordEmail;
    return this;
  }

   /**
   * 1Password user email to connect to the API
   * @return _1passwordEmail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1Password user email to connect to the API")

  public String get1passwordEmail() {
    return _1passwordEmail;
  }


  public void set1passwordEmail(String _1passwordEmail) {
    this._1passwordEmail = _1passwordEmail;
  }


  public GatewayMigratePersonalItems _1passwordPassword(String _1passwordPassword) {
    
    this._1passwordPassword = _1passwordPassword;
    return this;
  }

   /**
   * 1Password user password to connect to the API
   * @return _1passwordPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1Password user password to connect to the API")

  public String get1passwordPassword() {
    return _1passwordPassword;
  }


  public void set1passwordPassword(String _1passwordPassword) {
    this._1passwordPassword = _1passwordPassword;
  }


  public GatewayMigratePersonalItems _1passwordSecretKey(String _1passwordSecretKey) {
    
    this._1passwordSecretKey = _1passwordSecretKey;
    return this;
  }

   /**
   * 1Password user secret key to connect to the API
   * @return _1passwordSecretKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1Password user secret key to connect to the API")

  public String get1passwordSecretKey() {
    return _1passwordSecretKey;
  }


  public void set1passwordSecretKey(String _1passwordSecretKey) {
    this._1passwordSecretKey = _1passwordSecretKey;
  }


  public GatewayMigratePersonalItems _1passwordUrl(String _1passwordUrl) {
    
    this._1passwordUrl = _1passwordUrl;
    return this;
  }

   /**
   * 1Password api container url
   * @return _1passwordUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1Password api container url")

  public String get1passwordUrl() {
    return _1passwordUrl;
  }


  public void set1passwordUrl(String _1passwordUrl) {
    this._1passwordUrl = _1passwordUrl;
  }


  public GatewayMigratePersonalItems _1passwordVaults(List<String> _1passwordVaults) {
    
    this._1passwordVaults = _1passwordVaults;
    return this;
  }

  public GatewayMigratePersonalItems add1passwordVaultsItem(String _1passwordVaultsItem) {
    if (this._1passwordVaults == null) {
      this._1passwordVaults = new ArrayList<String>();
    }
    this._1passwordVaults.add(_1passwordVaultsItem);
    return this;
  }

   /**
   * 1Password list of vault to get the items from
   * @return _1passwordVaults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "1Password list of vault to get the items from")

  public List<String> get1passwordVaults() {
    return _1passwordVaults;
  }


  public void set1passwordVaults(List<String> _1passwordVaults) {
    this._1passwordVaults = _1passwordVaults;
  }


  public GatewayMigratePersonalItems json(Boolean json) {
    
    this.json = json;
    return this;
  }

   /**
   * Set output format to JSON
   * @return json
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Set output format to JSON")

  public Boolean getJson() {
    return json;
  }


  public void setJson(Boolean json) {
    this.json = json;
  }


  public GatewayMigratePersonalItems protectionKey(String protectionKey) {
    
    this.protectionKey = protectionKey;
    return this;
  }

   /**
   * The name of a key that used to encrypt the secret value
   * @return protectionKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of a key that used to encrypt the secret value")

  public String getProtectionKey() {
    return protectionKey;
  }


  public void setProtectionKey(String protectionKey) {
    this.protectionKey = protectionKey;
  }


  public GatewayMigratePersonalItems targetLocation(String targetLocation) {
    
    this.targetLocation = targetLocation;
    return this;
  }

   /**
   * Target location in your Akeyless personal folder for migrated secrets
   * @return targetLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Target location in your Akeyless personal folder for migrated secrets")

  public String getTargetLocation() {
    return targetLocation;
  }


  public void setTargetLocation(String targetLocation) {
    this.targetLocation = targetLocation;
  }


  public GatewayMigratePersonalItems token(String token) {
    
    this.token = token;
    return this;
  }

   /**
   * Authentication token (see &#x60;/auth&#x60; and &#x60;/configure&#x60;)
   * @return token
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Authentication token (see `/auth` and `/configure`)")

  public String getToken() {
    return token;
  }


  public void setToken(String token) {
    this.token = token;
  }


  public GatewayMigratePersonalItems type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Migration type for now only 1password.
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Migration type for now only 1password.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public GatewayMigratePersonalItems uidToken(String uidToken) {
    
    this.uidToken = uidToken;
    return this;
  }

   /**
   * The universal identity token, Required only for universal_identity authentication
   * @return uidToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The universal identity token, Required only for universal_identity authentication")

  public String getUidToken() {
    return uidToken;
  }


  public void setUidToken(String uidToken) {
    this.uidToken = uidToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GatewayMigratePersonalItems gatewayMigratePersonalItems = (GatewayMigratePersonalItems) o;
    return Objects.equals(this._1passwordEmail, gatewayMigratePersonalItems._1passwordEmail) &&
        Objects.equals(this._1passwordPassword, gatewayMigratePersonalItems._1passwordPassword) &&
        Objects.equals(this._1passwordSecretKey, gatewayMigratePersonalItems._1passwordSecretKey) &&
        Objects.equals(this._1passwordUrl, gatewayMigratePersonalItems._1passwordUrl) &&
        Objects.equals(this._1passwordVaults, gatewayMigratePersonalItems._1passwordVaults) &&
        Objects.equals(this.json, gatewayMigratePersonalItems.json) &&
        Objects.equals(this.protectionKey, gatewayMigratePersonalItems.protectionKey) &&
        Objects.equals(this.targetLocation, gatewayMigratePersonalItems.targetLocation) &&
        Objects.equals(this.token, gatewayMigratePersonalItems.token) &&
        Objects.equals(this.type, gatewayMigratePersonalItems.type) &&
        Objects.equals(this.uidToken, gatewayMigratePersonalItems.uidToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_1passwordEmail, _1passwordPassword, _1passwordSecretKey, _1passwordUrl, _1passwordVaults, json, protectionKey, targetLocation, token, type, uidToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GatewayMigratePersonalItems {\n");
    sb.append("    _1passwordEmail: ").append(toIndentedString(_1passwordEmail)).append("\n");
    sb.append("    _1passwordPassword: ").append(toIndentedString(_1passwordPassword)).append("\n");
    sb.append("    _1passwordSecretKey: ").append(toIndentedString(_1passwordSecretKey)).append("\n");
    sb.append("    _1passwordUrl: ").append(toIndentedString(_1passwordUrl)).append("\n");
    sb.append("    _1passwordVaults: ").append(toIndentedString(_1passwordVaults)).append("\n");
    sb.append("    json: ").append(toIndentedString(json)).append("\n");
    sb.append("    protectionKey: ").append(toIndentedString(protectionKey)).append("\n");
    sb.append("    targetLocation: ").append(toIndentedString(targetLocation)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uidToken: ").append(toIndentedString(uidToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

