/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * KMIPServer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class KMIPServer {
  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_CA = "ca";
  @SerializedName(SERIALIZED_NAME_CA)
  private List<Integer> ca = null;

  public static final String SERIALIZED_NAME_CERTIFICATE = "certificate";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE)
  private List<Integer> certificate = null;

  public static final String SERIALIZED_NAME_CERTIFICATE_ISSUE_DATE = "certificate_issue_date";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_ISSUE_DATE)
  private OffsetDateTime certificateIssueDate;

  public static final String SERIALIZED_NAME_CERTIFICATE_TTL_IN_SECONDS = "certificate_ttl_in_seconds";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_TTL_IN_SECONDS)
  private Long certificateTtlInSeconds;

  public static final String SERIALIZED_NAME_HOSTNAME = "hostname";
  @SerializedName(SERIALIZED_NAME_HOSTNAME)
  private String hostname;

  public static final String SERIALIZED_NAME_ROOT = "root";
  @SerializedName(SERIALIZED_NAME_ROOT)
  private String root;

  public KMIPServer() { 
  }

  public KMIPServer active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  public KMIPServer ca(List<Integer> ca) {
    
    this.ca = ca;
    return this;
  }

  public KMIPServer addCaItem(Integer caItem) {
    if (this.ca == null) {
      this.ca = new ArrayList<Integer>();
    }
    this.ca.add(caItem);
    return this;
  }

   /**
   * Get ca
   * @return ca
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getCa() {
    return ca;
  }


  public void setCa(List<Integer> ca) {
    this.ca = ca;
  }


  public KMIPServer certificate(List<Integer> certificate) {
    
    this.certificate = certificate;
    return this;
  }

  public KMIPServer addCertificateItem(Integer certificateItem) {
    if (this.certificate == null) {
      this.certificate = new ArrayList<Integer>();
    }
    this.certificate.add(certificateItem);
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Integer> getCertificate() {
    return certificate;
  }


  public void setCertificate(List<Integer> certificate) {
    this.certificate = certificate;
  }


  public KMIPServer certificateIssueDate(OffsetDateTime certificateIssueDate) {
    
    this.certificateIssueDate = certificateIssueDate;
    return this;
  }

   /**
   * Get certificateIssueDate
   * @return certificateIssueDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCertificateIssueDate() {
    return certificateIssueDate;
  }


  public void setCertificateIssueDate(OffsetDateTime certificateIssueDate) {
    this.certificateIssueDate = certificateIssueDate;
  }


  public KMIPServer certificateTtlInSeconds(Long certificateTtlInSeconds) {
    
    this.certificateTtlInSeconds = certificateTtlInSeconds;
    return this;
  }

   /**
   * Get certificateTtlInSeconds
   * @return certificateTtlInSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getCertificateTtlInSeconds() {
    return certificateTtlInSeconds;
  }


  public void setCertificateTtlInSeconds(Long certificateTtlInSeconds) {
    this.certificateTtlInSeconds = certificateTtlInSeconds;
  }


  public KMIPServer hostname(String hostname) {
    
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHostname() {
    return hostname;
  }


  public void setHostname(String hostname) {
    this.hostname = hostname;
  }


  public KMIPServer root(String root) {
    
    this.root = root;
    return this;
  }

   /**
   * Get root
   * @return root
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRoot() {
    return root;
  }


  public void setRoot(String root) {
    this.root = root;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KMIPServer kmIPServer = (KMIPServer) o;
    return Objects.equals(this.active, kmIPServer.active) &&
        Objects.equals(this.ca, kmIPServer.ca) &&
        Objects.equals(this.certificate, kmIPServer.certificate) &&
        Objects.equals(this.certificateIssueDate, kmIPServer.certificateIssueDate) &&
        Objects.equals(this.certificateTtlInSeconds, kmIPServer.certificateTtlInSeconds) &&
        Objects.equals(this.hostname, kmIPServer.hostname) &&
        Objects.equals(this.root, kmIPServer.root);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, ca, certificate, certificateIssueDate, certificateTtlInSeconds, hostname, root);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KMIPServer {\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    ca: ").append(toIndentedString(ca)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    certificateIssueDate: ").append(toIndentedString(certificateIssueDate)).append("\n");
    sb.append("    certificateTtlInSeconds: ").append(toIndentedString(certificateTtlInSeconds)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    root: ").append(toIndentedString(root)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

