/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.akeyless.client.JSON;

/**
 * PasswordBreachInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class PasswordBreachInfo {
  public static final String SERIALIZED_NAME_BREACH_CHECK_DATE = "breach_check_date";
  @SerializedName(SERIALIZED_NAME_BREACH_CHECK_DATE)
  @javax.annotation.Nullable
  private OffsetDateTime breachCheckDate;

  public static final String SERIALIZED_NAME_BREACH_COUNT = "breach_count";
  @SerializedName(SERIALIZED_NAME_BREACH_COUNT)
  @javax.annotation.Nullable
  private Long breachCount;

  public static final String SERIALIZED_NAME_BREACH_SUGGESTIONS = "breach_suggestions";
  @SerializedName(SERIALIZED_NAME_BREACH_SUGGESTIONS)
  @javax.annotation.Nullable
  private List<String> breachSuggestions = new ArrayList<>();

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public PasswordBreachInfo() {
  }

  public PasswordBreachInfo breachCheckDate(@javax.annotation.Nullable OffsetDateTime breachCheckDate) {
    this.breachCheckDate = breachCheckDate;
    return this;
  }

  /**
   * Get breachCheckDate
   * @return breachCheckDate
   */
  @javax.annotation.Nullable
  public OffsetDateTime getBreachCheckDate() {
    return breachCheckDate;
  }

  public void setBreachCheckDate(@javax.annotation.Nullable OffsetDateTime breachCheckDate) {
    this.breachCheckDate = breachCheckDate;
  }


  public PasswordBreachInfo breachCount(@javax.annotation.Nullable Long breachCount) {
    this.breachCount = breachCount;
    return this;
  }

  /**
   * Get breachCount
   * @return breachCount
   */
  @javax.annotation.Nullable
  public Long getBreachCount() {
    return breachCount;
  }

  public void setBreachCount(@javax.annotation.Nullable Long breachCount) {
    this.breachCount = breachCount;
  }


  public PasswordBreachInfo breachSuggestions(@javax.annotation.Nullable List<String> breachSuggestions) {
    this.breachSuggestions = breachSuggestions;
    return this;
  }

  public PasswordBreachInfo addBreachSuggestionsItem(String breachSuggestionsItem) {
    if (this.breachSuggestions == null) {
      this.breachSuggestions = new ArrayList<>();
    }
    this.breachSuggestions.add(breachSuggestionsItem);
    return this;
  }

  /**
   * Get breachSuggestions
   * @return breachSuggestions
   */
  @javax.annotation.Nullable
  public List<String> getBreachSuggestions() {
    return breachSuggestions;
  }

  public void setBreachSuggestions(@javax.annotation.Nullable List<String> breachSuggestions) {
    this.breachSuggestions = breachSuggestions;
  }


  public PasswordBreachInfo status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordBreachInfo passwordBreachInfo = (PasswordBreachInfo) o;
    return Objects.equals(this.breachCheckDate, passwordBreachInfo.breachCheckDate) &&
        Objects.equals(this.breachCount, passwordBreachInfo.breachCount) &&
        Objects.equals(this.breachSuggestions, passwordBreachInfo.breachSuggestions) &&
        Objects.equals(this.status, passwordBreachInfo.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(breachCheckDate, breachCount, breachSuggestions, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordBreachInfo {\n");
    sb.append("    breachCheckDate: ").append(toIndentedString(breachCheckDate)).append("\n");
    sb.append("    breachCount: ").append(toIndentedString(breachCount)).append("\n");
    sb.append("    breachSuggestions: ").append(toIndentedString(breachSuggestions)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("breach_check_date");
    openapiFields.add("breach_count");
    openapiFields.add("breach_suggestions");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PasswordBreachInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PasswordBreachInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PasswordBreachInfo is not found in the empty JSON string", PasswordBreachInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PasswordBreachInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PasswordBreachInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("breach_suggestions") != null && !jsonObj.get("breach_suggestions").isJsonNull() && !jsonObj.get("breach_suggestions").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `breach_suggestions` to be an array in the JSON string but got `%s`", jsonObj.get("breach_suggestions").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PasswordBreachInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PasswordBreachInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PasswordBreachInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PasswordBreachInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<PasswordBreachInfo>() {
           @Override
           public void write(JsonWriter out, PasswordBreachInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PasswordBreachInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PasswordBreachInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PasswordBreachInfo
   * @throws IOException if the JSON string is invalid with respect to PasswordBreachInfo
   */
  public static PasswordBreachInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PasswordBreachInfo.class);
  }

  /**
   * Convert an instance of PasswordBreachInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

