/*
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.akeyless.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.akeyless.client.JSON;

/**
 * SharingPolicyInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class SharingPolicyInfo {
  public static final String SERIALIZED_NAME_DEFAULT_SHARE_LINK_TTL = "default_share_link_ttl";
  @SerializedName(SERIALIZED_NAME_DEFAULT_SHARE_LINK_TTL)
  @javax.annotation.Nullable
  private Long defaultShareLinkTtl;

  public static final String SERIALIZED_NAME_ENABLE = "enable";
  @SerializedName(SERIALIZED_NAME_ENABLE)
  @javax.annotation.Nullable
  private Boolean enable;

  public SharingPolicyInfo() {
  }

  public SharingPolicyInfo defaultShareLinkTtl(@javax.annotation.Nullable Long defaultShareLinkTtl) {
    this.defaultShareLinkTtl = defaultShareLinkTtl;
    return this;
  }

  /**
   * Get defaultShareLinkTtl
   * @return defaultShareLinkTtl
   */
  @javax.annotation.Nullable
  public Long getDefaultShareLinkTtl() {
    return defaultShareLinkTtl;
  }

  public void setDefaultShareLinkTtl(@javax.annotation.Nullable Long defaultShareLinkTtl) {
    this.defaultShareLinkTtl = defaultShareLinkTtl;
  }


  public SharingPolicyInfo enable(@javax.annotation.Nullable Boolean enable) {
    this.enable = enable;
    return this;
  }

  /**
   * Get enable
   * @return enable
   */
  @javax.annotation.Nullable
  public Boolean getEnable() {
    return enable;
  }

  public void setEnable(@javax.annotation.Nullable Boolean enable) {
    this.enable = enable;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SharingPolicyInfo sharingPolicyInfo = (SharingPolicyInfo) o;
    return Objects.equals(this.defaultShareLinkTtl, sharingPolicyInfo.defaultShareLinkTtl) &&
        Objects.equals(this.enable, sharingPolicyInfo.enable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultShareLinkTtl, enable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SharingPolicyInfo {\n");
    sb.append("    defaultShareLinkTtl: ").append(toIndentedString(defaultShareLinkTtl)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("default_share_link_ttl");
    openapiFields.add("enable");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SharingPolicyInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SharingPolicyInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SharingPolicyInfo is not found in the empty JSON string", SharingPolicyInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SharingPolicyInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SharingPolicyInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SharingPolicyInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SharingPolicyInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SharingPolicyInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SharingPolicyInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<SharingPolicyInfo>() {
           @Override
           public void write(JsonWriter out, SharingPolicyInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SharingPolicyInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SharingPolicyInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SharingPolicyInfo
   * @throws IOException if the JSON string is invalid with respect to SharingPolicyInfo
   */
  public static SharingPolicyInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SharingPolicyInfo.class);
  }

  /**
   * Convert an instance of SharingPolicyInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

